### PR TITLE
initial antora v3 buildout

### PR DESCRIPTION
**Pull request by rasummer**
@ennru This updates the Akka guide to Antora 3 and the new Lightbend theme. 

I'm new to docker, so please take a close look at what I've done to `antora-docker/Dockerfile` . It works for me when I use `make local-preview`. 

Akka-Guide-Akka-Guide

### CODE REVIEW

**Review by ennru — APPROVED** [review]
Looks good.
I tiny touch of Akka-style would be good. The current pages have the Akka logo.

**Comment by rasummer** [comment]
> Looks good. I tiny touch of Akka-style would be good. The current pages have the Akka logo.

I'll find a place or two to add the Akka logo back in.

**Comment by rasummer** [comment]
Added the Akka Logo back in. @ennru 

image

**Review by ennru — APPROVED** [review]
LGTM.

**Pull request merged**
